* To Do
** TODO Wire up Nomad for configuration
** TODO Figure out deploying nomad secret files
** TODO The Great Renamening!
thermador -> voltron
*** TODO Rename in project
*** TODO Move voltron.cljs into project
** TODO Move from Joda -> clj-time
** Old Next steps
   - Nice to Haves [3/3]
     - [X] Make sync-redis do a more sensical job -- new version in dbx should overwrite.
     - [X] Main method for migration
     - [X] Heroku Scheduler

   - Good to do [1/2]
     - [ ] Clean up CORS, make sure it's sensible for dev vs prod.
       Maybe move CORS stuff into its own NS in config?
       - [ ] Update ring.cors to 0.1.4
     - [X] Refactoring pass. Delete cruft. Tidy oop.

   - Much harder [0/1]
     - [ ] Make prototype inheritance into ~defrecords~. /Woah/. Or not? Maybe just better type dispatch
       for multimethods.

** Redis Branch, closed <2014-08-31 Sun>
  - Before we merge Redis in to master [8/8]
    - [X] Make sure tests clean up after themselves properly.
    - [X] Do I actually have *anything* like test coverage?
    - [X] Integrate Dropbox with Redis
    - [X] Make sure that the Page REST API actually returns something that matches what
      ~frontend~ is expecting.
    - [X] ...is there a way to test a REST API?
      ring.mock, it seems? Give it a go.
    - [X] Clean up retrieve to stop passing ~model~. The model of a pobj is it's next-higher prototype.
    - [X] Need a ~remove~ function. Or delete.
    - [X] Logging pass

  - Prepping to deploy to For Real Heroku [1/1]
    - [X] Logging?
  - [2/2]
    - [X] Figure atoms out. Make this consistent
      This is.... better. Not great, but better.
    - [X] On that note: any item that is an atom needs to deal with that for keymaking.

  - Other/misc/eventually [2/2]
    - [X] Perhaps each level of a pobj should *say* what their lookup-key is?
      NOPE. Fuck that noise. Just agree that :datum-name is the name and call it good.
    - [X] What the *hell* lein? (Dev deps. I don't get it.)
      Files a bug report with technomancy. Will see.
